version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass mysecretpassword

  identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: indentity
    command: start-dev #--import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
      - 19000:9000

  workflow:
    image: docker.restate.dev/restatedev/restate:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8080:8080' # Ingress
      - '9070:9070' # Admin
    environment:
      - RESTATE_NODE_NAME=restate-1
      - RESTATE_FORCE_NODE_ID=1
      - RESTATE_AUTO_PROVISION=true
    volumes:
      - ./.restate-data:/restate-data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      # Jaeger UI (Web Interface)
      - '16686:16686'
      # Jaeger OTLP gRPC endpoint
      - '14250:14250'
      # Jaeger OTLP HTTP endpoint
      - '14268:14268'
    environment:
      # Disable health checks to avoid noise
      COLLECTOR_HEALTH_CHECK_HTTP_PORT: 0
      # Configure Jaeger to accept OTLP
      COLLECTOR_OTLP_ENABLED: true

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      # Mount the configuration file
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger
    ports:
      # OTLP gRPC port (Application trace data ingress)
      - '4317:4317'
      # OTLP HTTP port (Application log data ingress)
      - '4318:4318'
      # Collector pprof/ZPages for monitoring the collector itself
      - '55679:55679'

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always # Keep the service running
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # HTTP Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_log:
